name: 'Huawei Cloud Functiongraph Deploy'
description: 'Deploy Your Function to Huawei Cloud'
branding:
  icon: 'cloud'
  color: 'red'
author: 'wenchui'
inputs:
  ak: 
    required: true
    description: 'Huawei Cloud AK'
  sk: 
    required: true
    description: 'Huawei Cloud SK'
  endpoint: 
    required: true
    description: 'Huawei Cloud functiongraph endpoint'
    default: 'https://functiongraph.cn-north-4.myhuaweicloud.com'
  project_id: 
    required: true
    description: 'Huawei Cloud project_id'
  function_urn: 
    required: true
    description: 'Huawei Cloud functiongraph urn address'
  function_codetype: 
    required: true
    description: 'support obs, zip, jar, file, dir'
  function_file: 
    required: true
    description: 'obs url, local java jar path, local zip file path, local function file path, local directory path'
runs:
  using: 'node16'
  main: 'dist/index.js'
