name: "commit-master"

on:
  push:
    branches: 
    - 'master'
jobs:
  build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Check Out 
#       uses: actions/checkout@v2

    runs-on: ubuntu-latest
    steps:
      # 代码检出
    - name: checkout
      uses: actions/checkout@v2

    # 安装KooCLI
    - name: Setup KooCLI
      uses: huaweicloud/huaweicloud-cli-action@v1.0.1
      with:
        access_key: ${{ secrets.ACCESSKEY }}
        secret_key: ${{ secrets.SECRETACCESSKEY }}
        region: 'cn-north-4'

      # 查询KooCLI配置项
    - run: hcloud configure list

#     - name: deploy single function file to huaweicloud functiongraph
#       uses: ./
#       with:
#         ak: ${{ secrets.ACCESSKEY }}
#         sk: ${{ secrets.SECRETACCESSKEY }}
#         endpoint: https://functiongraph.cn-north-4.myhuaweicloud.com
#         project_id: 086cd4ee9e00268e2f76c00ea33b6cbe
#         function_codetype: zip
#         function_urn: urn:fss:cn-north-4:086cd4ee9e00268e2f76c00ea33b6cbe:function:default:func-dir2:latest
#         function_file: ./resource/zipfunction/index.zip
